@api = http://localhost:3020/api/pwa/institutes

### GET ALL INSTITUTES
GET {{api}}

### POST INSTITUTE
POST {{api}}
Content-Type: application/json

{
  "IdInstitutoOK": "743",
  "IdInstitutoBK": "67890",
  "IdInstitutoSupOK": "54321",
  "DesInstituto": "ibm",
  "Alias": "IE",
  "Matriz": "Matriz Ejemplo",
  "IdTipoGiroOK": "78901",
  "cat_negocios": [
    {
      "IdNegocioOK": "56789",
      "IdNegocioBK": "09876",
      "IdNegocioSupOK": "43210",
      "DesNegocio": "Negocio Principal",
      "Alias": "NP",
      "Matriz": "Matriz Negocio",
      "info_ad": [
        {
          "IdEtiquetaOK": "34567",
          "IdEtiqueta": "87654",
          "Etiqueta": "Etiqueta Ejemplo",
          "Valor": "Valor Ejemplo",
          "IdTipoSeccionOK": "21098",
          "Secuencia": 1,
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "archivos": [
        {
          "IdArchivoBK": "12345",
          "DesArchivo": "Archivo Ejemplo",
          "RutaArchivo": "/ruta/archivo",
          "IdTipoArchivoOK": "67890",
          "IdTipoSeccionOK": "09876",
          "Secuencia": 2,
          "Principal": "S",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "telefonos": [
        {
          "DesTelefono": "Teléfono Ejemplo",
          "CodPais": "+1",
          "NumTelefono": "123456789",
          "NumExtension": "001",
          "Principal": "S",
          "IdTipoTelefonoOK": "34567",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "dir_webs": [
        {
          "DesDirWeb": "Sitio Web Ejemplo",
          "DireccionWeb": "http://www.ejemplo.com",
          "IdTipoDirWebOK": "56789",
          "Principal": "S",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "domicilios": [
        {
          "DesDomicilio": "Domicilio Principal",
          "CalleNumero": "123 Main St",
          "EntreCalle1": "First St",
          "EntreCalle2": "Second St",
          "Referencia": "Referencia",
          "CodPostal": "12345",
          "Principal": "S",
          "CoordenadasXY": "40.7128,-74.0060",
          "IdTipoDomicilioOK": "78901",
          "Pais": "USA",
          "Estado": "NY",
          "Municipio": "New York",
          "Localidad": "Manhattan",
          "Colonia": "Downtown",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "detail_row": {
        "Activo": "S",
        "Borrado": "N",
        "detail_row_reg": [
          {
            "FechaReg": "2023-10-07T12:00:00.000Z",
            "UsuarioReg": "SYSTEM"
          }
        ]
      }
    }
  ],
  "detail_row": {
    "Activo": "S",
    "Borrado": "N",
    "detail_row_reg": [
      {
        "FechaReg": "2023-10-07T12:00:00.000Z",
        "UsuarioReg": "SYSTEM"
      }
    ]
  }
}

### PUT INSTITUTE
PUT {{api}}/743
Content-Type: application/json

{
  "IdInstitutoOK": "743",
  "IdInstitutoBK": "67890",
  "IdInstitutoSupOK": "54321",
  "DesInstituto": "Google",
  "Alias": "IE",
  "Matriz": "Matriz Ejemplo",
  "IdTipoGiroOK": "78901",
  "cat_negocios": [
    {
      "IdNegocioOK": "56789",
      "IdNegocioBK": "09876",
      "IdNegocioSupOK": "43210",
      "DesNegocio": "Negocio Principal",
      "Alias": "NP",
      "Matriz": "Matriz Negocio",
      "info_ad": [
        {
          "IdEtiquetaOK": "34567",
          "IdEtiqueta": "87654",
          "Etiqueta": "Etiqueta Ejemplo",
          "Valor": "Valor Ejemplo",
          "IdTipoSeccionOK": "21098",
          "Secuencia": 1,
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "archivos": [
        {
          "IdArchivoBK": "12345",
          "DesArchivo": "Archivo Ejemplo",
          "RutaArchivo": "/ruta/archivo",
          "IdTipoArchivoOK": "67890",
          "IdTipoSeccionOK": "09876",
          "Secuencia": 2,
          "Principal": "S",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "telefonos": [
        {
          "DesTelefono": "Teléfono Ejemplo",
          "CodPais": "+1",
          "NumTelefono": "123456789",
          "NumExtension": "001",
          "Principal": "S",
          "IdTipoTelefonoOK": "34567",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "dir_webs": [
        {
          "DesDirWeb": "Sitio Web Ejemplo",
          "DireccionWeb": "http://www.ejemplo.com",
          "IdTipoDirWebOK": "56789",
          "Principal": "S",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "domicilios": [
        {
          "DesDomicilio": "Domicilio Principal",
          "CalleNumero": "123 Main St",
          "EntreCalle1": "First St",
          "EntreCalle2": "Second St",
          "Referencia": "Referencia",
          "CodPostal": "12345",
          "Principal": "S",
          "CoordenadasXY": "40.7128,-74.0060",
          "IdTipoDomicilioOK": "78901",
          "Pais": "USA",
          "Estado": "NY",
          "Municipio": "New York",
          "Localidad": "Manhattan",
          "Colonia": "Downtown",
          "detail_row": {
            "Activo": "S",
            "Borrado": "N",
            "detail_row_reg": [
              {
                "FechaReg": "2023-10-07T12:00:00.000Z",
                "UsuarioReg": "SYSTEM"
              }
            ]
          }
        }
      ],
      "detail_row": {
        "Activo": "S",
        "Borrado": "N",
        "detail_row_reg": [
          {
            "FechaReg": "2023-10-07T12:00:00.000Z",
            "UsuarioReg": "SYSTEM"
          }
        ]
      }
    }
  ],
  "detail_row": {
    "Activo": "S",
    "Borrado": "N",
    "detail_row_reg": [
      {
        "FechaReg": "2023-10-07T12:00:00.000Z",
        "UsuarioReg": "SYSTEM"
      }
    ]
  }
}

### DELETE INSTITUTE
DELETE {{api}}/743